[package]
name = "erc20"
version = "0.1.0"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest

[lib]
name = "erc20"

[dependencies]
# foo = { path = "vendor/foo" }

[[target.starknet-contract]]